---
name: Unit Tests

on:
  pull_request:
  merge_group:
  push:
    tags:
      - 'v**'

permissions: {}

jobs:
  unit-testing:
    name: Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Run Go unit tests
        run: |
          set -o pipefail
          make unit
