---
name: Unit Tests

on:
  pull_request:
  push:
    tags:
      - 'v**'

permissions: {}

jobs:
  unit-testing:
    name: Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Run Go unit tests
        run: |
          set -o pipefail
          make unit
