---
name: Unit Tests

on:
  pull_request:
  push:
    tags:
      - 'v**'

permissions: {}

jobs:
  unit-testing:
    name: Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Run Go unit tests
        run: |
          set -o pipefail
          make unit
