---
name: Unit Tests

on:
  pull_request:
  merge_group:
  push:
    tags:
      - 'v**'

permissions: {}

jobs:
  unit-testing:
    name: Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Run Go unit tests
        run: |
          set -o pipefail
          make unit
